# Generated by Django 5.0.7 on 2024-08-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job_boardapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposting",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
